name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "5c64ab3989a44646b85223790f8675a8" },
  { binding = "SHARE", id = "a5b758dcd1c047cebf829658a9dc3500" }
]